### ISSUE TITLE
could we open another parameter for issue token - numbers for token?

### ISSUE THREAD

**Issue by bobjiang** [AlphaWallet/ERC875-token-factory#1]
could we open another parameter for issue token - numbers for token?

as above, e.g by default we will have 20 tokens, could we set the number?

maybe other parameters should be considered to open, not sure what else.

**Comment by JamesANZ** [comment]
hi @bobjiang I am weary of doing this as the gas limit starts to hit. Can do a PR to allow up to 20 tickets.
