### ISSUE TITLE
need to have a separate page for existing contract owner

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/ERC875-token-factory#21]
the main function for existing contract owner is to add more token any time.

**Comment by JamesANZ** [comment]
@zhangzhongnan928 we might find it more productive to use xcontract and fix it's appearance up. The reasoning behind this is that with xcontract we can do basically every smart contract function and with proper styling by @farrahfazirah it can be much more useful than a dedicated page. Of course we may have additional information which would warrant another page being created just for ticketing etc.

**Comment by zhangzhongnan928** [comment]
Agree, please close this issue. 

		
Victor Zhang
CEO, AlphaWallet
							
A 1000 DApps in your pocket — Why a wallet is so much more than an app to hold keys by James Sangalli https://t.co/BNjaA6ob2e	Read More
