### ISSUE TITLE
provide a function to get tokenID for each token in one 875 contract and 

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/ERC875-token-factory#29]
Provide a function to get tokenID for each token in one 875 contracts
Provide a function to upload metadata for each token like a picture 

Now：
1.  I can use TextEdit to put contract address and TokenID into a PNG picture file.
2. I can use https://globalupload.io/ to upload the PNG file to IPFS and the hash
3. I can use https://ipfs.github.io/public-gateway-checker/ to check or download the PNG file
4. This PNG file on IPFS is just a proof.
5. I can upload the PNG to normal online storage and use it in our ERC875-token-transfer DApp

**Comment by JamesANZ** [comment]
@zhangzhongnan928 

1. You mean like this? https://alphawallet.github.io/ERC875-token-transfer/
2. Isn't this what mokens does? Why reinvent the wheel? If I have misunderstood, please clarify further.

**Comment by zhangzhongnan928** [comment]
I am trying to link different metadata with each token.

Mokens only allows users to mint token with metadata, useless.
No asset issuer will use other people’s contract to issue asset. 

If we make a NFT token factory, need to allow user to burn contract + mint token + link metadata.

I'm thinking to kill the 875 token factory, keep the 875 ticket factory, make a new 721 compatible NFT token factory.

But this is a low priority thing. Changing the name from 875 token factory to NFT token factory can get the traffic from Google already. @bootingman wen make sure we get the Google search result display, of people searching NFT token factory.

		
Victor Zhang
CEO, AlphaWallet
							
A 1000 DApps in your pocket — Why a wallet is so much more than an app to hold keys by James Sangalli https://t.co/BNjaA6ob2e	Read More
